[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
FlatGeobuf = "d985ece1-97de-4d33-914c-38fb84042e15"
GeoArrow = "5bc3a8d9-1bfb-4624-ba94-a391279174d6"
GeoDataFrames = "62cb38b5-d8d2-4862-a48e-6a340996859f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoParquet = "e99870d8-ce00-4fdd-aeee-e09192881159"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"

[compat]
Documenter = "1"
DocumenterVitepress = "0.2.6"
